services:
  dst-master:
    container_name: dst-server-master
    image: dst-server:latest
    build:
      network: host
      context: build
    environment:
      - shard=Master
    volumes:
      - ./server-files:/home/steam/server-files
      - ./klei:/home/steam/.klei
    ports:
      - 10888
      - 10998-10999
      - 27017-27018
      - 8767-8768
    stdin_open: true
    tty: true

  dst-caves:
    container_name: dst-server-caves
    image: dst-server:latest
    environment:
      - shard=Caves
    network_mode: service:dst-master
    volumes:
      - ./server-files:/home/steam/server-files
      - ./klei:/home/steam/.klei
    stdin_open: true
    tty: true
    depends_on:
      - dst-master
    restart: always